### ISSUE TITLE
[feat] homie support

### ISSUE THREAD

**Issue by travisghansen** [OpenZWave/Zwave2Mqtt#128]
Any interest in supporting the `homie` spec?
- https://github.com/homieiot/convention

**Comment by robertsLando** [comment]
That would be interesting, unfortunally this would be a breaking change and would need some thoughts. Actually topics are not really different from that standard (and I never heard about that since now unfortunally) but if you have any suggestions we could think about a possible implementation.

Actually the topics looks like: `<prefix>/<?location>/<nodeName/id>/<valueId/valueTopic>`  
Where:
- `location` is optional
- `nodeName` is the node name if specified, if not the nodeid is used
- `valueTopic` is the value topic if specified, the value id if not

Homie expects: `<prefix>/<deviceId>/<node>/<attribute>`

Now an auto-mapped gateway that respects homie specifications is almost impossible but it is possible to get something really similar when using gateway in manual mode. In that mode (that is also the suggested one) you can manually specify the value topics so in case of a thermostat you can take the temperature value and set the value topic as `temperature` So for example you could get something like:

`z2m/kitchen/thermostat1/temperature`

Than for sure there wpuld need to support all others homie specs like `$name` $state` $extensions` `$properties` `$unit` `$datatype` that are not a problem since zwave already has lot informations about values and nodes.

What do you think? 

We could create a switch on gateway settings to support this specifications

**Comment by travisghansen** [comment]
Yeah I figured it would live pretty close to the hass code. My experience with zwave is limited and frustrating to say the least but I've some experience with node and homie..

**Comment by robertsLando** [comment]
Who else use homie specs? I mean, is home assistant for example using it?

**Comment by travisghansen** [comment]
Looks like there's a somewhat stale project implementing it in hass but my primary target is openhab at the moment. You can of course add the items manually in hass.

Given the number of libraries etc available for esp8266 and the like I presume it's used elsewhere as well.
