### ISSUE TITLE
[feat] Renaming entities

### ISSUE THREAD

**Issue by Dinth** [OpenZWave/Zwave2Mqtt#223]
**Is your feature request related to a problem? Please describe.**
Is there currently any way of renaming entities/values in Z2M? 
I've tried changing device name, but it keeps entities names the same. 
I've tried changing id in HASS Deviec JSON but it changes back to the old one as soon as i highlight a different device. 

**Describe the solution you'd like**
Maybe a button to rename nodes between "Store" and "Remove store" in Home Assistant - Devices section?

**Comment by robertsLando** [comment]
You mean `discovey_payload` `name` or `unique_id` props?

They aree calculated in this way actually:

```
 // Set a friendly name for this component
        payload.name = `${nodeName}_${hassDevice.object_id}`
        // set a unique id for the component
        payload.unique_id = `zwave2mqtt_` + payload.name
```

Where `nodeName` is:

```

**Comment by Dinth** [comment]
But thats generated only once and doesnt seem to change when for example Node Name changes. 
<img width="1503" alt="Screenshot 2020-01-27 at 13 19 43" src="https://user-images.githubusercontent.com/313674/73182256-a0b94500-4110-11ea-92c1-15741eaee71c.png">

**Comment by robertsLando** [comment]
That is a know bug and is in my todos :(

**Comment by robertsLando** [comment]
Wait sorry, the problem here with your configuration is that you have stored those entities (check the column `persistent`  `yes`. YOu should remove store to let z2m rediscover those values and the topic/name will be updated according to that. 


When store is enabled z2m on startup simply checks on the store and sends all the discovery payloads without recalculate them for each value. 

This could be improved by checking topics/name and updating them maybe

**Comment by Dinth** [comment]
Thanks @robertsLando i dont know how i could miss that!
