### ISSUE TITLE
[feat]Add (inclusion) securely

### ISSUE THREAD

**Issue by cts1085** [OpenZWave/Zwave2Mqtt#283]
**Is your feature request related to a problem? Please describe.**
I am trying to add new nodes to my ZWave network and they are not showing as added in a secure fashion - I do have a key established and some nodes added earlier (Before Zwave2mqtt) were added securely.

**Describe the solution you'd like**
Either assume inclusion is to be done securely or add an option to add secure

**Describe alternatives you've considered**
tried added a Zwave plus device and it was not added securely

**Additional context**
Zwave native to HA had this option

**Comment by robertsLando** [comment]
@cts1085 The secure flag you see there comes from a valueid that not all devices support. In order to start a secure inclusion you just have to start inclusion and a popup will show up asking if you want to start it in secure mode. The node could have secure set to false but it will be secured if added in this way
