### ISSUE TITLE
[bug] Lock User codes not hashed (shown in plain text in the UI and logs)

### ISSUE THREAD

**Issue by jaburges** [OpenZWave/Zwave2Mqtt#318]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.2
Openzwave Version: 1.6.1061

**Describe the bug**
In a previous lock (and a previous build) - I can't be certain as only have a single lock BE469ZP where this is an issue (it wasn't on 2.x.x and using BE469).

On submitting a user code, the code is shown in plain text in the UI, and then the logs.

**To Reproduce**
1. Go to Node
2. Click on node number of the lock
3. Expand 'User'
4. Scroll down to user code 4
5. Type user code
6. submit
7. view debug, and logs
8. code is visible in plain text

**Expected behavior**
previously as a code was submitted it was hashed in the UI. 
ie when `1234` was entered and submitted, once the lock confirmed the code was added it would show `****`

**Additional context**
Oddly the UI is also showing user code 1 & user code 2. The default user codes used for unlocking and locking the lock that come pre-programmed. Again previously this would show '****' as you would need the manual or need to view the back of the lock (requiring it to be unscrewed from the inside).
I can not decide if this is a security risk?
I'm leaning toward it being an issue if it is in the logs as if someone shared the OZW logs it would contain user codes to that person's lock.

**Comment by robertsLando** [comment]
@jaburges Actually I treat valueIds based on theyr type (string, list, byte ecc...), how could I detect if a valueId is something that I need to hash? @Fishwaldo

**Comment by Fishwaldo** [comment]
There was never any hashing - In 1.4 UserCodes were treated as Binary - As when we wrote 1.4 it wasn't clear if they were ascii, binary or decimal. (due to RFID devices "abusing" the protocol). You could have easily decoded the Binary back to strings in 1.4

In 1.6, its clear UserCodes are treated as Strings, hence that's what is shown. Its upto a application to decide if they want to "hide" the codes or not. Removing them in the Logs is a LOT harder, as we log Raw packets recieved before we even know what the packet is about.

**Comment by robertsLando** [comment]
@Fishwaldo is there any command class-index should be everytime hidden? I mean I could create a function to identify values that should be hased and use an input password for them

**Comment by jaburges** [comment]
This worked previously - not sure what changed.
The code entered would stay in the UI `user code slot 1` - when the lock had accepted it, it then converted it to ****

What i'm saying is it worked before in the UI, and now it doesn't. I cant confirm this did or did not happen in the logs

**Comment by robertsLando** [comment]
@jaburges I don't convert anything to **** in the UI, there was never such support, so that was something received from OZW, if so

**Comment by jaburges** [comment]
@robertsLando weird that it has now stopped hashing user codes.
If that is the case can you implement an optional login screen to prevent anyone on my network getting to the Z2M dashboard?
My MQTT is secured, but this is a simple way to get in.

**Comment by robertsLando** [comment]
A login screen is already in my todo list but it requires some major changes to be implemented, nothing that will come in the near future because I have very little time now. What you could do is to use nginx to create a basic authentication: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by Fishwaldo** [comment]
>This worked previously - not sure what changed.
They were binary before, they are now strings in 1.6

Nothing Robert did "hashed" previously. He probably just couldn't/didn't decode binary (ValueRaw) values previously.

**Comment by jaburges** [comment]
ok, seems like the best approach is to create a user login screen. I'll close this and check if there is already a FR
