### ISSUE TITLE
[bug] Battery level for some devices gets reported as a different device

### ISSUE THREAD

**Issue by jshridha** [OpenZWave/Zwave2Mqtt#325]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.2
Openzwave Version: 1.6-1061-g14f2ba74

**Describe the bug**
With my firstalert zwave devices, the battery level gets reported under the device: zwave2mqtt_laundry_first_alert whereas the other sensors get reported under the new unique identifier format: zwave2mqtt_0xe6ebd3e1_node42. This causes the entities to be separated in home assistant.

Please see the photographs below for demonstration.
![image](https://user-images.githubusercontent.com/11232787/77485211-f5bcc300-6e02-11ea-9c71-468a51456ef7.png)

![image](https://user-images.githubusercontent.com/11232787/77485234-040adf00-6e03-11ea-91bb-d23ec125d24e.png)

**Comment by robertsLando** [comment]
@jshridha Sorry this is not really a bug, in fact if you check your screenshot you will see that the sensor_battery has `persistent` set to `Yes`. Remove it from persistence and it will work :) It's just because you may have stored it with a prev vesion of z2m and it keeps the old identifier of when you stored it
