### ISSUE TITLE
[question] How to add additional device types / Unknown type.

### ISSUE THREAD

**Issue by jaredgudnason** [OpenZWave/Zwave2Mqtt#361]
Hi there, new to your project.  thanks for all the work, so far so good.
I've deployed zwave2mqtt in a docker using the container image: robertslando/zwave2mqtt:latest
been slowly adding devices, which for the most part go okay, but i'm running into issues with a couple.

the first is an Inovelli sensor, which adds okay, but comes up ans an unknown type.  This is where my knowlege gets very fuzzy, i found the following gethub: https://github.com/InovelliUSA/OpenZWave which i think has their device definitions, but i have no idea where to apply that (or if that is even the issue).  So that's question 1.

Question 2, i have one device that when i set configuration values, it doesn't stick.  If i set, then hit the refresh button on the page, it stays changed.. but if i switch pages (like to config) and back to devices, the setting is back to its original value.  I dont see any errors in the debug log, and at this point i'm assuming it's a hardware issue, as no other device exhibits this behavior, but though i would still mention it.

Thanks for any input or help!

**Comment by robertsLando** [comment]
>  found the following gethub: https://github.com/InovelliUSA/OpenZWave which i think has their device definitions, but i have no idea where to apply that (or if that is even the issue)

It's already installed in the docker container along with its devices db. 

Please enable auto update device db zwave setting in order to make an auto update of the db.

>  i have one device that when i set configuration values, it doesn't stick. If i set, then hit the refresh button on the page, it stays changed

When you select a configuration than you need to hit the airplain button on the right. So a notification should appear with 'Value Updated' to confirm the change is done correctly. After a container restart you need to press on refresh to see the actual configuration values
