### ISSUE TITLE
Gateway configured manually does not show all devices - at least not if same type

### ISSUE THREAD

**Issue by KennethLavrsen** [OpenZWave/Zwave2Mqtt#38]
I am trying to setup Gateway configured manually

I have one Aeotec stick and two identical sirens.

When I want to setup the topics manually for the sirens I can only see one.

I see the stick and one siren. So I cannot use the feature at all

**Comment by robertsLando** [comment]
If you mean you see one device per type I assume that you are trying to add devices in the gateway values table, that table holds the configurations of the gateway and it is correct that there is just one per type because it is used to configure which values you want to push to mqtt for each device type. All your values are added in the table in the section `Control Panel`
