### ISSUE TITLE
[feat] Missing field for configuring the volume of a supported tone

### ISSUE THREAD

**Issue by petrovcicklemen** [OpenZWave/Zwave2Mqtt#479]
**Is your feature request related to a problem? Please describe.**
I am testing a device, that supported CC_SOUND_SWITCH. The Zwave2MQTT gui shows a control for playing the supported tones, but doesn't offer a control for configuring its volume.

**Describe the solution you'd like**
An option for configuring the volume of a supported tone. Two inputs fiedls (one for toneId, the other for the volume value). This woudl map to the SOUND_SWITCH.SOUND_SWITCH_CONFIGURATION_SET.

**Describe alternatives you've considered**
Not much to do. OpenZWave_v1.6 apparently already supports this command, it is only absent from the control panel.

**Additional context**
I've attached a gif, that shows the shown input controls. At the end, there is a control for playing/muting the supported tone, but no control for configuring the volume.
![SupportedToneVolume](https://user-images.githubusercontent.com/19154318/81819889-2df19f80-9530-11ea-8ec6-32d8f44aa46c.gif)

**Comment by robertsLando** [comment]
@petrovcicklemen Please open this question on Openzwave repo. I haven't control of that, every value you see comes from there and if it isn't there could be related to a configuration problem in the device xml

**Comment by petrovcicklemen** [comment]
@robertsLando: Thank you.

@Fishwaldo Hi Justin. I have a question about CC_SOUND_SWITCH. I've tested our [Luxy Light](https://github.com/OpenZWave/open-zwave/blob/master/config/qubino/ZMNHQDx.xml) product, that supports this command class on Zwave2Mqtt that uses OpenZwave_v1.6.1115. The control panel shows the option for playing/muting a tone, but not for configuring its volume. Last time we talked about this, it was said, that OpenZwave already supports this volume configuration command. I was wondering, if we have to add anything to the configuration file?

**Comment by Fishwaldo** [comment]
For Other devices - The [Volume ValueID is exposed](https://github.com/OpenZWave/open-zwave/blob/1d7f512f3bb9b304fae25fafaf6d3073956b7210/cpp/src/command_classes/SoundSwitch.cpp#L325). You can grep the Log files to see if you get a ValueAdded notification for "Volume" (index 2 - ValueID_Index_SoundSwitch::Volume)

Should be noted that its exposed as a Config Genre so it may appear in a different section than the standard values (I don't know how Z2M displays Config Genre ValueID's)

@robertsLando Can you please do some basic troubleshooting before flicking things over to me. I barely have the bandwidth to support developers using OZW, let along end users (Klemen is a obvious exception being a vendor in this case, but you have been sending a lot my way lately that is not a bug) 

Please either send them to the right place (the Wiki/Mailing lists for OZW etc) rather than just blindly asking them to open tickets.

Better yet - Many other applications have a forum/discourse presence where a lot of users share/support themselves - given the growth of z2m it would be great if you could consider the same

**Comment by petrovcicklemen** [comment]
I apologise, the "Volume" field is present in the control panel and it works. The reason I didn't see it yesterday was, that it is placed under the "Configuration" section. I expected it to be under the section "User".

![sound](https://user-images.githubusercontent.com/19154318/81907601-5036fc00-95c8-11ea-875c-2d0735fc0379.PNG)

**Comment by robertsLando** [comment]
> Can you please do some basic troubleshooting before flicking things over to me

@Fishwaldo this kind of issues are mostly related to OZW if the user didn't see the value isn't my fault :confused: 

> Many other applications have a forum/discourse presence where a lot of users share/support themselves

I alreay have a slack channel for that but as mentioned above if a user has compatibility issues with a device I usually point it to your library as I can't do much on my side. Anyway I got it will redirect them to the OZW google groups forum or where you prefer
